cask_args appdir: "/Applications"

tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "anyenv"
brew "bat"
brew "exa"
brew "git"
brew "heroku"
brew "mas"
brew "peco"
brew "rsync"
brew "tree"
brew "wget"

cask "alfred"
cask "appcleaner"
cask "bettertouchtool"
cask "box-drive"
cask "cheatsheet"
cask "deepl"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "keyboardcleantool"
cask "kindle"
cask "microsoft-edge"
cask "ocenaudio"
cask "skitch"
cask "slack"
cask "sourcetree"
cask "tableplus"
cask "the-unarchiver"
cask "virtualbox"
cask "vagrant"
cask "visual-studio-code"
cask "zoom"
