Vagrant.configure("2") do |config|

  config.vm.define "test" do |test|
    test.vm.box = "bento/centos-7.7"
    test.vm.hostname = "test"
    test.vm.network "forwarded_port", guest: 80, host: 10080
    test.vm.network "private_network", ip: "192.168.33.10"
    test.vm.synced_folder ".", "/root"
    test.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
    test.vm.provision "shell", inline: <<-SHELL
      /root/dotfiles/link.sh
    SHELL
    test.ssh.username = 'root'
    test.ssh.password = 'vagrant'
    test.ssh.insert_key = 'true'
  end

end
