Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.7"
  config.vm.synced_folder ".", "/home/vagrant"

  config.vm.define "dev" do |dev|
    dev.vm.hostname = "dev"
    dev.vm.network "forwarded_port", guest: 80, host: 10080
    dev.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.inventory_path = "inventory"
    ansible.limit = "all"
  end
end
