Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.7"
  config.vm.synced_folder '.', '/home/vagrant'

  config.vm.define "dev" do |dev|
    dev.vm.hostname = "dev"
    dev.vm.network :private_network, ip: '192.168.33.10'
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'off']
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'off']
  end
end
