cask_args appdir: "/Applications"

tap "aws/tap"

# brew "anyenv"
brew "awsume"
# brew "aws-sam-cli"
brew "bash-completion"
# brew "bitwarden-cli"
brew "blueutil"
# brew "cfn-lint"
brew "docker"
# brew "eslint"
brew "gh"
brew "git"
brew "git-secrets"
brew "hadolint"
brew "jq"
brew "mas"
brew "pre-commit"
# brew "pylint"
# brew "rsync"
# brew "serverless"
brew "shellcheck"
brew "sleepwatcher"
brew "terraform-docs"
brew "tflint"
brew "tfsec"
brew "tree"
brew "watch"
brew "wget"

cask "appcleaner"
cask "aws-vault"
cask "cheatsheet"
# cask "dbeaver-community"
# cask "discord"
cask "firefox"
# cask "google-chrome"
cask "keyboardcleantool"
# cask "kindle"
cask "notion"
# cask "parallels-client"
cask "postman"
cask "rancher"
cask "raycast"
# cask "slack"
cask "the-unarchiver"
cask "visual-studio-code"
# cask "zoom"
# cask "1password-cli"
