cask_args appdir: "/Applications"

tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "anyenv"
brew "bash-completion"
brew "exa"
brew "git"
brew "git-secrets"
# brew "heroku"
brew "jq"
brew "mas"
brew "rsync"
brew "shellcheck"
brew "tree"
brew "watch"
brew "wget"

cask "alfred"
cask "appcleaner"
cask "aws-vault"
# cask "bettertouchtool"
cask "cheatsheet"
cask "clipy"
# cask "discord"
cask "docker"
cask "firefox"
# cask "google-chrome"
# cask "google-japanese-ime"
# cask "hyperswitch"
cask "iterm2"
cask "keyboardcleantool"
# cask "kindle"
cask "notion"
# cask "ocenaudio"
# cask "parallels-client"
cask "rectangle"
cask "simplenote"
# cask "skitch"
# cask "slack"
cask "sourcetree"
cask "the-unarchiver"
cask "visual-studio-code"
# cask "zoom"

# mas "BetterSnapTool", id: 417375580
# mas "LINE", id: 539883307
# mas "KakaoTalk", id: 869223134
# mas "Magnet", id: 441258766
# mas "Todoist", id: 585829637
