cask_args appdir: "/Applications"

# tap "domt4/autoupdate"

# brew "awsume"
brew "bash-completion"
brew "blueutil"
brew "coreutils"
brew "curl"
brew "deck"
brew "docker"
brew "ffmpeg"
brew "gawk"
# brew "gh"
brew "git"
brew "git-secrets"
brew "gpg"
brew "grep"
brew "gzip"
brew "jq"
brew "libyaml"
brew "mas"
brew "mise"
brew "pinact"
brew "pinentry-mac"
brew "ripgrep"
brew "sleepwatcher"
brew "terminal-notifier"
brew "tree"
brew "watch"
brew "wget"
brew "zsh-completion"

cask "appcleaner"
# cask "aws-vault"
cask "claude"
cask "claude-code"
cask "codex"
cask "codex-app"
cask "coteditor"
# cask "discord"
cask "drawio"
cask "firefox"
# cask "google-chrome"
cask "keyboardcleantool"
# cask "kindle"
cask "kiro-cli"
cask "notion"
cask "rancher"
cask "raycast"
# cask "slack"
cask "the-unarchiver"
cask "visual-studio-code"
# cask "zoom"
